# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.pagebreak_api import PagebreakApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPagebreakApi(unittest.TestCase):
    """PagebreakApi unit test stubs"""

    def setUp(self):
        self.api = PagebreakApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_pagebreak_delete(self):
        """Test case for pagebreak_delete

        """
        pass

    def test_pagebreak_get(self):
        """Test case for pagebreak_get

        """
        pass

    def test_pagebreak_patch(self):
        """Test case for pagebreak_patch

        """
        pass

    def test_pagebreak_post(self):
        """Test case for pagebreak_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
