# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.introspection_api import IntrospectionApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIntrospectionApi(unittest.TestCase):
    """IntrospectionApi unit test stubs"""

    def setUp(self):
        self.api = IntrospectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_root_get(self):
        """Test case for root_get

        OpenAPI description (this document)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
