# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scene_api import SceneApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSceneApi(unittest.TestCase):
    """SceneApi unit test stubs"""

    def setUp(self):
        self.api = SceneApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_scene_delete(self):
        """Test case for scene_delete

        """
        pass

    def test_scene_get(self):
        """Test case for scene_get

        """
        pass

    def test_scene_patch(self):
        """Test case for scene_patch

        """
        pass

    def test_scene_post(self):
        """Test case for scene_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
