# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.note_api import NoteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNoteApi(unittest.TestCase):
    """NoteApi unit test stubs"""

    def setUp(self):
        self.api = NoteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_note_delete(self):
        """Test case for note_delete

        """
        pass

    def test_note_get(self):
        """Test case for note_get

        """
        pass

    def test_note_patch(self):
        """Test case for note_patch

        """
        pass

    def test_note_post(self):
        """Test case for note_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
