# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.act_api import ActApi  # noqa: E501
from swagger_client.rest import ApiException


class TestActApi(unittest.TestCase):
    """ActApi unit test stubs"""

    def setUp(self):
        self.api = ActApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_act_delete(self):
        """Test case for act_delete

        """
        pass

    def test_act_get(self):
        """Test case for act_get

        """
        pass

    def test_act_patch(self):
        """Test case for act_patch

        """
        pass

    def test_act_post(self):
        """Test case for act_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
