# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parenthetical_api import ParentheticalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestParentheticalApi(unittest.TestCase):
    """ParentheticalApi unit test stubs"""

    def setUp(self):
        self.api = ParentheticalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_parenthetical_delete(self):
        """Test case for parenthetical_delete

        """
        pass

    def test_parenthetical_get(self):
        """Test case for parenthetical_get

        """
        pass

    def test_parenthetical_patch(self):
        """Test case for parenthetical_patch

        """
        pass

    def test_parenthetical_post(self):
        """Test case for parenthetical_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
