# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.character_api import CharacterApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCharacterApi(unittest.TestCase):
    """CharacterApi unit test stubs"""

    def setUp(self):
        self.api = CharacterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_character_delete(self):
        """Test case for character_delete

        """
        pass

    def test_character_get(self):
        """Test case for character_get

        """
        pass

    def test_character_patch(self):
        """Test case for character_patch

        """
        pass

    def test_character_post(self):
        """Test case for character_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
