# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.crossreferences import Crossreferences  # noqa: E501
from swagger_client.rest import ApiException


class TestCrossreferences(unittest.TestCase):
    """Crossreferences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrossreferences(self):
        """Test Crossreferences"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.crossreferences.Crossreferences()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
