# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.act import Act  # noqa: E501
from swagger_client.rest import ApiException


class TestAct(unittest.TestCase):
    """Act unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAct(self):
        """Test Act"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.act.Act()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
