# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Characterrelationship(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'relationship_id': 'int',
        'character1_id': 'int',
        'character2_id': 'int',
        'relationship_type': 'str'
    }

    attribute_map = {
        'relationship_id': 'relationship_id',
        'character1_id': 'character1_id',
        'character2_id': 'character2_id',
        'relationship_type': 'relationship_type'
    }

    def __init__(self, relationship_id=None, character1_id=None, character2_id=None, relationship_type=None):  # noqa: E501
        """Characterrelationship - a model defined in Swagger"""  # noqa: E501
        self._relationship_id = None
        self._character1_id = None
        self._character2_id = None
        self._relationship_type = None
        self.discriminator = None
        self.relationship_id = relationship_id
        if character1_id is not None:
            self.character1_id = character1_id
        if character2_id is not None:
            self.character2_id = character2_id
        if relationship_type is not None:
            self.relationship_type = relationship_type

    @property
    def relationship_id(self):
        """Gets the relationship_id of this Characterrelationship.  # noqa: E501

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The relationship_id of this Characterrelationship.  # noqa: E501
        :rtype: int
        """
        return self._relationship_id

    @relationship_id.setter
    def relationship_id(self, relationship_id):
        """Sets the relationship_id of this Characterrelationship.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param relationship_id: The relationship_id of this Characterrelationship.  # noqa: E501
        :type: int
        """
        if relationship_id is None:
            raise ValueError("Invalid value for `relationship_id`, must not be `None`")  # noqa: E501

        self._relationship_id = relationship_id

    @property
    def character1_id(self):
        """Gets the character1_id of this Characterrelationship.  # noqa: E501

        Note: This is a Foreign Key to `character.character_id`.<fk table='character' column='character_id'/>  # noqa: E501

        :return: The character1_id of this Characterrelationship.  # noqa: E501
        :rtype: int
        """
        return self._character1_id

    @character1_id.setter
    def character1_id(self, character1_id):
        """Sets the character1_id of this Characterrelationship.

        Note: This is a Foreign Key to `character.character_id`.<fk table='character' column='character_id'/>  # noqa: E501

        :param character1_id: The character1_id of this Characterrelationship.  # noqa: E501
        :type: int
        """

        self._character1_id = character1_id

    @property
    def character2_id(self):
        """Gets the character2_id of this Characterrelationship.  # noqa: E501

        Note: This is a Foreign Key to `character.character_id`.<fk table='character' column='character_id'/>  # noqa: E501

        :return: The character2_id of this Characterrelationship.  # noqa: E501
        :rtype: int
        """
        return self._character2_id

    @character2_id.setter
    def character2_id(self, character2_id):
        """Sets the character2_id of this Characterrelationship.

        Note: This is a Foreign Key to `character.character_id`.<fk table='character' column='character_id'/>  # noqa: E501

        :param character2_id: The character2_id of this Characterrelationship.  # noqa: E501
        :type: int
        """

        self._character2_id = character2_id

    @property
    def relationship_type(self):
        """Gets the relationship_type of this Characterrelationship.  # noqa: E501


        :return: The relationship_type of this Characterrelationship.  # noqa: E501
        :rtype: str
        """
        return self._relationship_type

    @relationship_type.setter
    def relationship_type(self, relationship_type):
        """Sets the relationship_type of this Characterrelationship.


        :param relationship_type: The relationship_type of this Characterrelationship.  # noqa: E501
        :type: str
        """

        self._relationship_type = relationship_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Characterrelationship, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Characterrelationship):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
