# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Musicsound(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'music_sound_id': 'int',
        'scene_id': 'int',
        'cue': 'str',
        'description': 'str'
    }

    attribute_map = {
        'music_sound_id': 'music_sound_id',
        'scene_id': 'scene_id',
        'cue': 'cue',
        'description': 'description'
    }

    def __init__(self, music_sound_id=None, scene_id=None, cue=None, description=None):  # noqa: E501
        """Musicsound - a model defined in Swagger"""  # noqa: E501
        self._music_sound_id = None
        self._scene_id = None
        self._cue = None
        self._description = None
        self.discriminator = None
        self.music_sound_id = music_sound_id
        if scene_id is not None:
            self.scene_id = scene_id
        if cue is not None:
            self.cue = cue
        if description is not None:
            self.description = description

    @property
    def music_sound_id(self):
        """Gets the music_sound_id of this Musicsound.  # noqa: E501

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The music_sound_id of this Musicsound.  # noqa: E501
        :rtype: int
        """
        return self._music_sound_id

    @music_sound_id.setter
    def music_sound_id(self, music_sound_id):
        """Sets the music_sound_id of this Musicsound.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param music_sound_id: The music_sound_id of this Musicsound.  # noqa: E501
        :type: int
        """
        if music_sound_id is None:
            raise ValueError("Invalid value for `music_sound_id`, must not be `None`")  # noqa: E501

        self._music_sound_id = music_sound_id

    @property
    def scene_id(self):
        """Gets the scene_id of this Musicsound.  # noqa: E501

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :return: The scene_id of this Musicsound.  # noqa: E501
        :rtype: int
        """
        return self._scene_id

    @scene_id.setter
    def scene_id(self, scene_id):
        """Sets the scene_id of this Musicsound.

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :param scene_id: The scene_id of this Musicsound.  # noqa: E501
        :type: int
        """

        self._scene_id = scene_id

    @property
    def cue(self):
        """Gets the cue of this Musicsound.  # noqa: E501


        :return: The cue of this Musicsound.  # noqa: E501
        :rtype: str
        """
        return self._cue

    @cue.setter
    def cue(self, cue):
        """Sets the cue of this Musicsound.


        :param cue: The cue of this Musicsound.  # noqa: E501
        :type: str
        """

        self._cue = cue

    @property
    def description(self):
        """Gets the description of this Musicsound.  # noqa: E501


        :return: The description of this Musicsound.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Musicsound.


        :param description: The description of this Musicsound.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Musicsound, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Musicsound):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
