# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Transition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'transition_id': 'int',
        'scene_id': 'int',
        'transition_text': 'str'
    }

    attribute_map = {
        'transition_id': 'transition_id',
        'scene_id': 'scene_id',
        'transition_text': 'transition_text'
    }

    def __init__(self, transition_id=None, scene_id=None, transition_text=None):  # noqa: E501
        """Transition - a model defined in Swagger"""  # noqa: E501
        self._transition_id = None
        self._scene_id = None
        self._transition_text = None
        self.discriminator = None
        self.transition_id = transition_id
        if scene_id is not None:
            self.scene_id = scene_id
        if transition_text is not None:
            self.transition_text = transition_text

    @property
    def transition_id(self):
        """Gets the transition_id of this Transition.  # noqa: E501

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :return: The transition_id of this Transition.  # noqa: E501
        :rtype: int
        """
        return self._transition_id

    @transition_id.setter
    def transition_id(self, transition_id):
        """Sets the transition_id of this Transition.

        Note: This is a Primary Key.<pk/>  # noqa: E501

        :param transition_id: The transition_id of this Transition.  # noqa: E501
        :type: int
        """
        if transition_id is None:
            raise ValueError("Invalid value for `transition_id`, must not be `None`")  # noqa: E501

        self._transition_id = transition_id

    @property
    def scene_id(self):
        """Gets the scene_id of this Transition.  # noqa: E501

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :return: The scene_id of this Transition.  # noqa: E501
        :rtype: int
        """
        return self._scene_id

    @scene_id.setter
    def scene_id(self, scene_id):
        """Sets the scene_id of this Transition.

        Note: This is a Foreign Key to `scene.scene_id`.<fk table='scene' column='scene_id'/>  # noqa: E501

        :param scene_id: The scene_id of this Transition.  # noqa: E501
        :type: int
        """

        self._scene_id = scene_id

    @property
    def transition_text(self):
        """Gets the transition_text of this Transition.  # noqa: E501


        :return: The transition_text of this Transition.  # noqa: E501
        :rtype: str
        """
        return self._transition_text

    @transition_text.setter
    def transition_text(self, transition_text):
        """Sets the transition_text of this Transition.


        :param transition_text: The transition_text of this Transition.  # noqa: E501
        :type: str
        """

        self._transition_text = transition_text

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Transition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Transition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
