# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.props_api import PropsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPropsApi(unittest.TestCase):
    """PropsApi unit test stubs"""

    def setUp(self):
        self.api = PropsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_props_delete(self):
        """Test case for props_delete

        """
        pass

    def test_props_get(self):
        """Test case for props_get

        """
        pass

    def test_props_patch(self):
        """Test case for props_patch

        """
        pass

    def test_props_post(self):
        """Test case for props_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
