# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.character import Character  # noqa: E501
from swagger_client.rest import ApiException


class TestCharacter(unittest.TestCase):
    """Character unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCharacter(self):
        """Test Character"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.character.Character()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
