# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sectionheading_api import SectionheadingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSectionheadingApi(unittest.TestCase):
    """SectionheadingApi unit test stubs"""

    def setUp(self):
        self.api = SectionheadingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sectionheading_delete(self):
        """Test case for sectionheading_delete

        """
        pass

    def test_sectionheading_get(self):
        """Test case for sectionheading_get

        """
        pass

    def test_sectionheading_patch(self):
        """Test case for sectionheading_patch

        """
        pass

    def test_sectionheading_post(self):
        """Test case for sectionheading_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
