# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.props import Props  # noqa: E501
from swagger_client.rest import ApiException


class TestProps(unittest.TestCase):
    """Props unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProps(self):
        """Test Props"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.props.Props()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
