# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.scenelocation_api import ScenelocationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScenelocationApi(unittest.TestCase):
    """ScenelocationApi unit test stubs"""

    def setUp(self):
        self.api = ScenelocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_scenelocation_delete(self):
        """Test case for scenelocation_delete

        """
        pass

    def test_scenelocation_get(self):
        """Test case for scenelocation_get

        """
        pass

    def test_scenelocation_patch(self):
        """Test case for scenelocation_patch

        """
        pass

    def test_scenelocation_post(self):
        """Test case for scenelocation_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
