# coding: utf-8

"""
    standard public schema

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 12.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dialogue_api import DialogueApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDialogueApi(unittest.TestCase):
    """DialogueApi unit test stubs"""

    def setUp(self):
        self.api = DialogueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dialogue_delete(self):
        """Test case for dialogue_delete

        """
        pass

    def test_dialogue_get(self):
        """Test case for dialogue_get

        """
        pass

    def test_dialogue_patch(self):
        """Test case for dialogue_patch

        """
        pass

    def test_dialogue_post(self):
        """Test case for dialogue_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
